name: CI

on:
  push: 
    branches:
    - '**'
  pull_request: {}

jobs:

  test:
    name: Test
    environment: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Test
      env:
        OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
      run: |
        go test -v ./... -coverprofile cover.out -tags=e2e
